name: 'Jinja2'
description: 'Use the Jinja2 templating engine'
inputs:
  template:
    required: true
  output_file:
    required: true
  strict:
    required: false
    default: false
  variables:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'sliders'
  color: 'red'
